name: feuzion
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sliding_card: ^0.1.2
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  percent_indicator: ^4.0.1
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.1
  cloud_firestore: ^4.0.1
  firebase_storage: ^11.0.1
  
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1

dev_dependencies: 
  flutter_lints: ^2.0.0

  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf




